# Generated by Django 4.2.4 on 2023-10-02 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballMatches',
            fields=[
                ('id_match', models.AutoField(primary_key=True, serialize=False)),
                ('score_hosts', models.PositiveIntegerField()),
                ('score_visitors', models.PositiveIntegerField()),
                ('phase', models.CharField(max_length=13)),
                ('start', models.DateTimeField()),
                ('isPenalties', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FootballTeams',
            fields=[
                ('id_team', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('group', models.CharField(choices=[('A', 'Group A'), ('B', 'Group B'), ('C', 'Group C'), ('D', 'Group D'), ('E', 'Group E'), ('F', 'Group F'), ('G', 'Group G'), ('H', 'Group H')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Penalties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalties_team1', models.PositiveIntegerField()),
                ('penalties_team2', models.PositiveIntegerField()),
                ('id_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting_game.footballmatches')),
            ],
        ),
        migrations.CreateModel(
            name='Guesses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guess_hosts_score', models.PositiveIntegerField()),
                ('guess_visitors_score', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField(default=0)),
                ('id_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_guesses', to='betting_game.footballmatches')),
            ],
        ),
    ]
