# Generated by Django 4.2.4 on 2023-09-20 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting_game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballMatches',
            fields=[
                ('id_match', models.AutoField(primary_key=True, serialize=False)),
                ('score_hosts', models.PositiveIntegerField()),
                ('score_visitors', models.PositiveIntegerField()),
                ('phase', models.CharField(max_length=13)),
                ('start', models.DateTimeField()),
                ('isPenalties', models.BooleanField(default=False)),
                ('id_hosts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_matches', to='betting_game.footballteams')),
                ('id_visitors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_matches', to='betting_game.footballteams')),
            ],
        ),
    ]
