# Generated by Django 4.2.4 on 2023-09-20 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting_game', '0002_footballmatches_penalties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalties_team1', models.PositiveIntegerField()),
                ('penalties_team2', models.PositiveIntegerField()),
                ('id_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting_game.footballmatches')),
            ],
        ),
    ]
