# Generated by Django 4.2.4 on 2023-09-28 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('betting_game', '0003_penalties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guesses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guess_hosts_score', models.PositiveIntegerField()),
                ('guess_visitors_score', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField(default=0)),
                ('id_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_guesses', to='betting_game.footballmatches')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_guesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
